type:build:
  - ".github/**/*"
  - ".coveralls.yml"
  - ".gitignore"
  - "ecs.yml"
  - "phpcs.xml"

dependencies:
  - "composer.json"

type:helpers:
  - "src/Helpers/**/*"

type:indexes:
  - "src/Compilers/Traits/WheresBuilder.php"
  - "src/Compilers/CheckCompiler.php"
  - "src/Compilers/ExcludeCompiler.php"
  - "src/Compilers/UniqueCompiler.php"
  - "src/Schema/Builders/Indexes/**/*"
  - "src/Schema/Builders/Constraints/**/*"
  - "src/Schema/Builders/WhereBuilderTrait.php"
  - "src/Schema/Definitions/CheckDefinition.php"
  - "src/Schema/Definitions/ExcludeDefinition.php"
  - "src/Schema/Definitions/UniqueDefinition.php"

type:routines:
  - "src/Compilers/Routines/**/*"
  - "src/Schema/Builders/Routines/**/*"
  - "src/Schema/Definitions/Routines/**/*"

type:schema:
  - "src/Schema/**/*"

type:compilers:
  - "src/Compilers/**/*"

type:tests:
  - 'tests/**/*'
  - 'phpunit.xml.dist'
  - 'tests.sh'

theme:docs:
  - "README.md"
  - "LICENSE"
  - "CONTRIBUTING.md"
  - "CODE_OF_CONDUCT.md"
  - "src/.meta.php"
